development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: portfolio_production
  pool: 5
